# Language Philosophy 

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# Numpy

Core library for computations, specifically, it allows creating arrays and doing operations on them. Arrays are n-dimensional objects of the same data type.

In [3]:
import numpy as np #common way to call this library

### 1D and 2D arrays

Create a 1-dimentional array.

In [ ]:
my_1D_array = #YOUR CODE GOES HERE

Print it out.

In [ ]:
my_1D_array

Check if it is an array by typing

In [ ]:
type(my_1D_array)

Check the dimensions of the array.

In [ ]:
#YOUR CODE GOES HERE

Let the second entry of the array to be 22 (hint: remember that indexes start at zero in Python). 

In [ ]:
#YOUR CODE GOES HERE

Create a 2-dimentional array.

In [ ]:
my_2D_array = #YOUR CODE GOES HERE

Print it out.

In [ ]:
my_2D_array

See what transpose() function or .T do to your 2D array.

In [ ]:
#YOUR CODE GOES HERE

In [ ]:
#YOUR CODE GOES HERE

Check if it is an array by typing

In [ ]:
type(my_2D_array)

Check the dimensions of the array.

In [ ]:
#YOUR CODE GOES HERE

Let the row with index 1 and column with index 1 of the array to be 22.

In [ ]:
#YOUR CODE GOES HERE

Create 2D array with shape (3, 7).

In [ ]:
my_2D_array = #YOUR CODE GOES HERE

Check if the shape is correct

In [ ]:
#YOUR CODE GOES HERE

In [ ]:
my_2D_array

### Slicing 

Slice your array (create a subarray) consisting of the first 2 rows and first 2 columns. The shape of new  array should be (2, 2).

In [ ]:
#YOUR CODE GOES HERE

Slice your array (create a subarray) consisting of the last 2 rows and the last 5 columns. The shape of new  array should be (2, 5).

In [ ]:
#YOUR CODE GOES HERE

In [ ]:
#YOUR CODE GOES HERE

Slicing with Booleans

In [4]:
boolean_mask = (my_2D_array > 5)   
boolean_mask

NameError: name 'my_2D_array' is not defined

In [ ]:
my_2D_array[boolean_mask] #notice it converted 2D array into 1D array!

You can do it in one shot.

In [ ]:
#YOUR CODE GOES HERE

### Initializing arrays

Explore fast ways to initialize different types of arrays.

a) array of zeros of shape (10,10), data type should be floats:

In [ ]:
array_of_zeros_floats = #YOUR CODE GOES HERE
array_of_zeros_floats

b) array of zeros of shape (7,7), data type should be integers:

In [ ]:
array_of_zeros_integers = #YOUR CODE GOES HERE
array_of_zeros_integers

c) array of ones of shape (7,7), data type should be floats:

In [ ]:
array_of_zeros_ones = #YOUR CODE GOES HERE
array_of_zeros_ones

d) array of random numbers of shape (5, 10) between 0 and 1:

In [ ]:
array_of_random_numbers = #YOUR CODE GOES HERE
array_of_random_numbers

e) array of random integers of shape (5, 10) between 0 and 100:

In [ ]:
array_of_random_integers = #YOUR CODE GOES HERE
array_of_random_integers

Check what arange() is doing

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Elementwise operations on arrays

In [5]:
first_array = np.array([[1, 2, 3],[4, 5, 6]])
second_array = np.array([[7, 8, 9],[10, 11, 12]])
print(first_array, '\n','\n', second_array)

[[1 2 3]
 [4 5 6]] 
 
 [[ 7  8  9]
 [10 11 12]]


One array and one constant

In [ ]:
first_array * 5

One array and one function

In [ ]:
np.sqrt(first_array)

Note that sum function behaves differently.

In [ ]:
np.sum(first_array)

In [ ]:
np.sum(first_array, axis=0) #applies to every column

In [ ]:
np.sum(first_array, axis=1) #applies to every row

#### Two arrays

a) sum:

In [ ]:
first_array + second_array

b) difference:

In [ ]:
first_array - second_array

c) product:

In [ ]:
first_array * second_array

d) division:

In [ ]:
first_array / second_array

# Your Own Functions

In [ ]:
def multiply_by_three(x):
    """
    This function multiplys the input by 3
    ---
    Input: Numerical
    Output: Numerical
    """
    return 3*x

In [ ]:
multiply_by_three(3)

In [ ]:
phone_dict = {'Mike': '555-122-363', 
             'Peter': '888-111-344',
             'Jane': '888-333-666',
             'Kate': '667-524-567'}
phone_dict

In [ ]:
def get_all_area_numbers(area_code, phone_dict=phone_dict):
    """
    This function finds all numbers by area_code from the dictionary phone_dict
    ---
    Input: Numerical, Dictionary
    Output: Dictionary
    """
    
    #YOUR CODE GOES HERE
        
    return new_dict

In [ ]:
get_all_area_numbers(area_code=888, phone_dict=phone_dict)